apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermgmt-webapp
spec:
  selector:
    matchLabels:
      app: webapp 
  template:
    metadata:
      labels:
        app: webapp 
    spec:
      containers:
      - name: webapp 
        image: gopal1409/user-mgt
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: DB_HOSTNAME
            value: "mysql-service"
          - name: DB_PORT
            value: "3306"
          - name: DB_NAME 
            value: "webappdb"
          - name: DB_USERNAME 
            value: "root"
          - name: DB_PASSWORD 
            valueFrom:
              secretKeyRef:
                name: my-db-password
                key: password
          
#DB_HOSTNAME=yourrdsdb.cxojydmxwly6.us-east-1.rds.amazonaws.com
#DB_PORT=3306
#DB_NAME=webappdb
#DB_USERNAME=dbadmin
#DB_PASSWORD=dbpassword11
