##how to create a pod defination. already it is being predefined by kubernetes.io dcument. 
###once we create any manifest file to apply the manifest file
##kubectl apply -f nameoftheyaml file. 
apiVersion: v1 
kind: Pod ##we want to invoke the pod api and want to create an pod with a container inside it. 
metadata:
  name: nginx #but when we created this pod we need to provide a name to the pod . using metadata name we provide the name of the pod
spec: #then we provide the specification of the pod
  containers: #the name of the container
  - name: nginx #the name of the container
    image: nginx:1.14.2 ##this is image of the container
    ports: ##this is the container pod
    - containerPort: 80 
