apiVersion: v1
kind: PersistentVolume
##once you create this persistent volume this will be avaialbe as a resource to your k8s cluster. 
metadata:
  name: task-pv-volume
spec:
  capacity:
    storage: 10Gi #it will be thin provisioning. if from 10Gb i am using 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce #readwritemany read
  hostPath:
    path: /mnt/data
  #persistentVolumeReclaimPolicy: Recycle
  #storageClassName: slow
  #mountOptions:
  #  - hard
  #  - nfsvers=4.1
  #nfs:
   # path: /tmp
    #server: 172.17.0.2
